version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
      - image: int128/sshd:latest
        environment:
          # see the keys in os-integration-test/etc/ssh/
          SSH_AUTHORIZED_KEYS: |
            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDvyn/5Z5s4TjxpCTJT0csJ7MeARchWzppcofSuAGaWeY0gR/vLxNZ1DupBPV6x7GGYZKkKP+n2JJ95ZO/TAbtPQfrq2hS24HtmVXeIQNhdJ5gFgplv5wAEOGX1t8Vy4tHlcMGtMYp+JvIup8YiHW6uic9QMaE5/3Q2DobllAQr17yDgEU9catR70FKqisemlOUaYc9KQWa3gZ8d6rHtfaAI1HnK6U7rH9ZzXmejyvSt6NhT7iQ2yJMF0HOpdQmnDqxJr5jOeWrgf0TbwW0AN3TXrqLFpUdy2DCWF0XEMOaLZhINMV1yxShYAUzhqbnP0voKoKv8IaSG/htJKAVIXn9
            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1xN7CzvOi8IOUqXs+y7BvCwr52enPvcaObR5ymVMZKwPiXXqNKOnvQsKv23JxSOfoHS7WeWqTCkxrawsTSB6ZO7qy6AHxF1qa26KGuwkgbAa7wZIAQtrAH/li04jllxDKYdcriq76poVVvK76q6ASxAy76eboWDrABBXhNWD1pHZj5pE0vKpdGRnAqe/vWIkkmJLy5cVwcrKz8RThtTYv1w5Wuzp2z4W7+O9oFXvYr76lztxLSMtgGcoM6hRUdn+CfBP4aN8LBr0MnvAcQec2aZUOEBFl8q73ZRQ10SmZciIaLEBI/MrB0Oa/TY48/FcQjwaFmQdyp2AIG/tQdzmx your_email@example.com
            ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmU+yuKZZrxAE61hYT1sm0cOKbUie5d61zXPw4ehgWiwyZYtEmH+pDmh/MZfxB6W8QUxOj/ClSYGtbnrDuFm1Y=
          SSH_HOST_RSA_KEY: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAQEAvQA/tTTYSOslnkBwHcQ3dQ+09adHECgRQk0y9+3PZv4EQaN48MzF
            hlqjLM8RUfKnoIVp3yHdo0uEZaDYWD5nyePSnOihIV0sx5gOoJdGhzligcQnhhC2EKoBOy
            u23NnT7Qx+ObgLxZYD28rsYD5WREp5Xj8Lv7BdQzuH3z+4l0CTOrSYok2dP+InqMBBiR+k
            k1UXOqcD6YeipIuzlrhqOceN07zON/dm9RGOY040So3mCKcn0TJ2wYB+bHLkimC6kgaiCy
            TWIGI/7yiwTuYDJYhAqCTPaaABoz6k4LdDr9+7mjTADRQseFf7VcKFT7kiSfbrUNSkGxKQ
            +Mw/w7EfgQAAA9Cj8Rn7o/EZ+wAAAAdzc2gtcnNhAAABAQC9AD+1NNhI6yWeQHAdxDd1D7
            T1p0cQKBFCTTL37c9m/gRBo3jwzMWGWqMszxFR8qeghWnfId2jS4RloNhYPmfJ49Kc6KEh
            XSzHmA6gl0aHOWKBxCeGELYQqgE7K7bc2dPtDH45uAvFlgPbyuxgPlZESnlePwu/sF1DO4
            ffP7iXQJM6tJiiTZ0/4ieowEGJH6STVRc6pwPph6Kki7OWuGo5x43TvM4392b1EY5jTjRK
            jeYIpyfRMnbBgH5scuSKYLqSBqILJNYgYj/vKLBO5gMliECoJM9poAGjPqTgt0Ov37uaNM
            ANFCx4V/tVwoVPuSJJ9utQ1KQbEpD4zD/DsR+BAAAAAwEAAQAAAQEAhfWOMi6ReiWJFUCQ
            9tgjgooudcspmC7+BKNZE9dvoI08kRV/3BUXj6HgdBsUKKQ34ZOONcP4JwyYe7vke69Hux
            YKKoLL6izzV0jUXUi7iY7H3jgc124yzV7h3oGea6zNBABN2zUyysoIVBnhLlogpOiwW3eO
            KUCk6clhBYBRoom/OpCnvx0K6RW2m9rmj9IdSt5XkIqR+e4idP4f4FMIUprX2fUbCtpyvz
            1bC3B19dhLqi1hnQKHw8UAQIUXzwSlgSmbf/KO56Lm4kN4KsIOiG8jjRqe8y2Zz40j3jfP
            ERdjh3Gx8opRb2iSZO2N48dltm+iPHe/pSvNGdz1ZfQAAQAAAIEAt+/7p7AI1vKBHtB8ra
            iG8ShaFRD32i5rILVI+UEp7NKi48Xm36LLbxgJZwNGsF4DGcimMfdjyHy7J1aB6BleuKUX
            iHRQFus26iU6jW7pqSIG9UAEONxO2smv8AjpU9t6oWmWj91osiuykMWcKrnKYgR7tB+BsS
            hIVqJagkn1jdwAAACBAOkRQheAz7c8hDnz3nnTBF0fACL8/yH4igChrYA29L1EdKgH1FwW
            RZIix6ROxZunYlbbdLhx2XXJnu07ffROVNku6bBK+XIHyrQlrUEU4xmKzwbmh2sBv78T6u
            WqmEj/YfIx7aX0G+i5GWfPhKdwvMJI1ZATEv7OVGo2DO6HoFWBAAAAgQDPmP/yfdxCxtWK
            GY1MANtFh/b2xWgSPRasbTg3L3LEk2I3WiQPcARTLv9O02ZNrwBSPJ33BF5GEkUcK13WI3
            P3ns3YHA031EPwQrF1T0iHN024EkDl0KKUMjobSOeoC1RmXHuJ6Do3lHHNxlvrkIKw3YxV
            92rSZ1v9fq2p3xnKAQAAABVoaWRldGFrZUByYWJiaXQubG9jYWwBAgME
            -----END OPENSSH PRIVATE KEY-----
          SSH_HOST_DSA_KEY: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABswAAAAdzc2gtZH
            NzAAAAgQDB5zSCWJEMYMspTanQt0tRR4JhDaDASR+RL84DfQX7Q1XuPG2YpHslB2G0D530
            4xPG7KdbpaTH3zZS8e6WfGKahtSX0+gUZWwpECin/UZdjDiXNz6XJ1ZEoCRLkid+yArXi6
            3BcDcNoPPNwyyMpvR9kNmGprh9G7qUtWDMYNul0wAAABUAjde0V4ohDO7KYPO4drK3AuIm
            vfEAAACBAMBFlUuR/RekINTvSbl1+5/iHYv4BULhCSYtTNuOMfidizLIYTDd0uzDxGZwf3
            SumhU6j74ew221mBK9C6y0m3v6lcOfa6M+QGrmaI2ciXDSmpxZYdT+RDpMcOZsURAY087F
            hxXbLSjCnBzfBfx8vJLOCaQs5qy6HAVm34z8YNeqAAAAgQCWuDOZWIaKghws6Pa6yoyZA9
            MMyhgV7HM6KQnAP0XQ+33dRsUVsiCgtgBL/uImkFtOJhrsHEA0pHOG4Cor9Hzyo4Ur57ln
            7kR2IUxhPKm4OyW3meH4gcAVBN1jYnmwZqRgF+7hi6tZNhEzr7VG6N92LpAQ+6Rao4QEAo
            m8DnT5yAAAAfDnggvs54IL7AAAAAdzc2gtZHNzAAAAgQDB5zSCWJEMYMspTanQt0tRR4Jh
            DaDASR+RL84DfQX7Q1XuPG2YpHslB2G0D5304xPG7KdbpaTH3zZS8e6WfGKahtSX0+gUZW
            wpECin/UZdjDiXNz6XJ1ZEoCRLkid+yArXi63BcDcNoPPNwyyMpvR9kNmGprh9G7qUtWDM
            YNul0wAAABUAjde0V4ohDO7KYPO4drK3AuImvfEAAACBAMBFlUuR/RekINTvSbl1+5/iHY
            v4BULhCSYtTNuOMfidizLIYTDd0uzDxGZwf3SumhU6j74ew221mBK9C6y0m3v6lcOfa6M+
            QGrmaI2ciXDSmpxZYdT+RDpMcOZsURAY087FhxXbLSjCnBzfBfx8vJLOCaQs5qy6HAVm34
            z8YNeqAAAAgQCWuDOZWIaKghws6Pa6yoyZA9MMyhgV7HM6KQnAP0XQ+33dRsUVsiCgtgBL
            /uImkFtOJhrsHEA0pHOG4Cor9Hzyo4Ur57ln7kR2IUxhPKm4OyW3meH4gcAVBN1jYnmwZq
            RgF+7hi6tZNhEzr7VG6N92LpAQ+6Rao4QEAom8DnT5yAAAABQcGgS2uRxbrfvcxPwmL/Mq
            JOcO3QAAABVoaWRldGFrZUByYWJiaXQubG9jYWwBAgME
            -----END OPENSSH PRIVATE KEY-----
          SSH_HOST_ECDSA_KEY: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAaAAAABNlY2RzYS
            1zaGEyLW5pc3RwMjU2AAAACG5pc3RwMjU2AAAAQQTb2Qpge+BrGw6SKfi2lTzubUPS5FYg
            OGJBOV3IgNGJOP4q+lQZV4KQCq+XgtDsL3OxAOFya/sa3dNI90Sh5ZXoAAAAsOBC60DgQu
            tAAAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNvZCmB74GsbDpIp
            +LaVPO5tQ9LkViA4YkE5XciA0Yk4/ir6VBlXgpAKr5eC0Owvc7EA4XJr+xrd00j3RKHlle
            gAAAAgQhtKq9f2GGDeivbuZ3tPKWtzabtWWkBBMCP79B1WIhcAAAAVaGlkZXRha2VAcmFi
            Yml0LmxvY2FsAQID
            -----END OPENSSH PRIVATE KEY-----
          SSH_HOST_ED25519_KEY: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
            QyNTUxOQAAACAg0uc6mInMIv6tF/4rYU5Tn/VBZ0Wp7HSzBqMQDLwPqgAAAJi6uxPeursT
            3gAAAAtzc2gtZWQyNTUxOQAAACAg0uc6mInMIv6tF/4rYU5Tn/VBZ0Wp7HSzBqMQDLwPqg
            AAAEDtQZ8yklhUquVEgewNF+kCFYADJ5vOQqrAfqWZ1XpiryDS5zqYicwi/q0X/ithTlOf
            9UFnRansdLMGoxAMvA+qAAAAFWhpZGV0YWtlQHJhYmJpdC5sb2NhbA==
            -----END OPENSSH PRIVATE KEY-----
    working_directory: ~/groovy-ssh
    steps:
      - run: mkdir -p $HOME/bin
      - run: echo 'export PATH="$HOME/bin:$PATH"' >> $BASH_ENV
      - run: |
          curl -L -o $HOME/bin/ghcp https://github.com/int128/ghcp/releases/download/v1.3.0/ghcp_linux_amd64
          chmod +x $HOME/bin/ghcp
      - run: |
          curl -L -o /tmp/ghr.tar.gz https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_amd64.tar.gz
          tar -C /tmp -zxf /tmp/ghr.tar.gz
          mv /tmp/ghr_v0.12.0_linux_amd64/ghr $HOME/bin/ghr
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: ./gradlew build
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: |
          if [ "$CIRCLE_BRANCH" = "master" ]; then
            ./.circleci/release-docs.sh
          fi
      - run: |
          if [ "$CIRCLE_TAG" ]; then
            ./.circleci/release-cli.sh
            ./gradlew bintrayUpload
          fi

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
            tags:
              only: /.*/
