= Getting Started

== Use Gradle SSH Plugin

=== Requirement

Gradle SSH Plugin requires following:

* Java 6 or later
* Gradle 2.0 or later (Gradle 1.x is also supported with the backport library)


=== Create a project

==== Clone the template project

Get the https://github.com/gradle-ssh-plugin/template[Gradle SSH Plugin Template Project] for quick start.
The project contains Gradle wrapper, so Gradle installation is not needed.

We can clone the template project as follows:

[source,sh]
----
git clone https://github.com/gradle-ssh-plugin/template.git awesome-ssh
cd awesome-ssh
./gradlew tasks --all
----

We can open the project with an IDE such as IntelliJ IDEA.


==== Use an existent project

Of course we can add the plugin to an existent project.


=== Add the plugin dependency

The plugin is available on the Gradle plugin registry.
Gradle will fetch the plugin from Internet.

Add the plugin to your script as follows:

[source,groovy,subs="+attributes"]
----
plugins {
  id 'org.hidetake.ssh' version '{gradle-ssh-version}'
}
----

Gradle 2.0 style:

[source,groovy,subs="+attributes"]
----
buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath 'org.hidetake:gradle-ssh-plugin:{gradle-ssh-version}'
  }
}

apply plugin: 'org.hidetake.ssh'
----


==== Use on Gradle 1.x

The plugin also supports Gradle 1.x with the backport library:

[source,groovy,subs="+attributes"]
----
buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath 'org.hidetake:gradle-ssh-plugin:{gradle-ssh-version}'
    classpath 'org.codehaus.groovy:groovy-backports-compat23:2.4.6'
  }
}

apply plugin: 'org.hidetake.ssh'
----


=== Add a remote host

The plugin adds a container of remote hosts to the project.
One or more remote hosts can be added in the `remotes` closure.
A remote host can be associated with one or more roles.

Following code adds remote hosts to the remote hosts container:

[source,groovy]
----
remotes {
  web01 {
    role 'masterNode'
    host = '192.168.1.101'
    user = 'jenkins'
  }
  web02 {
    host = '192.168.1.102'
    user = 'jenkins'
  }
}
----

We can specify each remote host by `remotes.web01` or `remotes.web02`.
Also we can specify the remote host _web01_ by a role such as `remotes.role('masterNode')`.

All settings of a remote host are available on link:user-guide.html#add-a-remote-host[the user guide].


=== Describe SSH sessions

Call `ssh.run` method with one or more sessions as follows.

[source,groovy]
----
task checkWebServers << {
  ssh.run {
    session(remotes.web01) {
      // Execute a command
      def result = execute 'sudo service httpd status'

      // Any Gradle methods or properties are available in a session closure
      copy {
        from "src/main/resources/example"
        into "$buildDir/tmp"
      }

      // Also Groovy methods or properties are available in a session closure
      println result
    }
    session(remotes.web02) {
      def result = execute 'sudo service httpd status'

      // Also Groovy style assertion is available in a session closure
      assert result.contains('running')
    }
  }
}
----


=== Run the script

Now the script is ready.

[source,groovy,subs="+attributes"]
----
plugins {
  id 'org.hidetake.ssh' version '{gradle-ssh-version}'
}

ssh.settings {
  dryRun = project.hasProperty('dryRun')
}

remotes {
  web01 {
    role 'webServers'
    host = '192.168.1.101'
    user = 'jenkins'
    identity = file('id_rsa')
  }
  web02 {
    role 'webServers'
    host = '192.168.1.102'
    user = 'jenkins'
    identity = file('id_rsa')
  }
}

task reload << {
  ssh.run {
    session(remotes.role('webServers')) {
      execute 'sudo service tomcat restart'
    }
  }
}
----

Invoke the task to run.

[source,sh]
----
./gradlew reload
----


==== Dry run the script

We can run the script without any actual connections.

Above script has already dry-run switch,
so invoke the task with `dryRun` property to perform dry-run.

[source,sh]
----
./gradlew -PdryRun -i reload
----


== Use Groovy SSH

NOTE: work in progress
