name: release

on:
  pull_request:
    paths:
      - .github/workflows/release.yaml
      - gradle/**
      - '**/*.gradle'
  release:
    types:
      - created

jobs:
  plugin:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: 11
      - uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      - run: ./gradlew validatePlugins

      - run: echo "$GRADLE_PROPERTIES_PUBLISH" >> ~/.gradle/gradle.properties
        env:
          GRADLE_PROPERTIES_PUBLISH: ${{ secrets.GRADLE_PROPERTIES_PUBLISH }}
      - if: github.event_name == 'release'
        run: ./gradlew publishPlugins
        env:
          VERSION: ${{ github.event.release.tag_name }}

  maven:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: 11
      - uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      - run: ./gradlew sign
        env:
          VERSION: ${{ github.event.release.tag_name }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}

      - if: github.event_name == 'release'
        run: ./gradlew publishToMavenCentral
        env:
          VERSION: ${{ github.event.release.tag_name }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

  cli:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: 11
      - uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      - run: ./gradlew shadowJar
      - run: java -jar groovy-ssh/cli/build/libs/gssh.jar
      - run: sha256sum -b groovy-ssh/cli/build/libs/gssh.jar > groovy-ssh/cli/build/libs/gssh.jar.sha256
      - if: github.event_name == 'release'
        run: gh release upload "$VERSION" groovy-ssh/cli/build/libs/gssh.jar groovy-ssh/cli/build/libs/gssh.jar.sha256
        env:
          VERSION: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
